name: Build
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/test.yml'
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
