name: Tag Image
on:
  workflow_dispatch:
    inputs:
      src:
        description: Source tag
        required: true
      dst:
        description: Destination tags (space-separated)
        required: true
permissions:
  packages: write
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - id: owner
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}
      - name: Install crane
        env:
          VERSION: "0.12.1"
        run: |
          curl -fsSL "https://github.com/google/go-containerregistry/releases/download/v${VERSION}/go-containerregistry_Linux_x86_64.tar.gz" | tar zxf - crane
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        env:
          SRC: "ghcr.io/${{ steps.owner.outputs.lowercase }}/codespaces-nix:${{ inputs.src }}"
          DST: "${{ inputs.dst }}"
        run: |
          IFS=' ' read -r -a dst_tags <<< "$DST"
          for t in "${dst_tags[@]}"; do
            ./crane tag "$SRC" "$t"
          done
